name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    needs: [lint, build, test]
    if: github.event.pusher.name != 'github-actions[bot]'
    runs-on: [self-hosted, kubernetes, haskell-runner]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/devenv-action@v2
      - run: devenv tasks run hackage:sdist
      - name: Upload to Hackage
        run: |
          curl -H "X-ApiKey: ${{ secrets.HACKAGE_API_KEY }}"           -T dist-newstyle/sdist/*.tar.gz           https://hackage.haskell.org/packages/
